import { assertBackOfficeData } from "./model.mjs";

export const demoBackOfficeData = {
  tenants: [
    {
      id: "tenant-migration-demo",
      tenant_id: "tenant-migration-demo",
      vertical: "migration",
      name: "Migration Demo Tenant",
      workspace: "agentic-back-office-demo",
      data_classification: "synthetic_pii",
    },
    {
      id: "tenant-hr-demo",
      tenant_id: "tenant-hr-demo",
      vertical: "hr",
      name: "HR Demo Tenant",
      workspace: "agentic-back-office-demo",
      data_classification: "synthetic_pii",
    },
  ],
  people: [
    { id: "person-mig-agent", tenant_id: "tenant-migration-demo", roles: ["migration_agent"], display_name: "Maya Demo", email: "maya.demo@example.com" },
    { id: "person-amina-hart", tenant_id: "tenant-migration-demo", roles: ["applicant"], display_name: "Amina Hart", email: "amina.hart@example.com" },
    { id: "person-rahul-hart", tenant_id: "tenant-migration-demo", roles: ["sponsor"], display_name: "Rahul Hart", email: "rahul.hart@example.com" },
    { id: "person-daniel-cho", tenant_id: "tenant-migration-demo", roles: ["applicant"], display_name: "Daniel Cho", email: "daniel.cho@example.com" },
    { id: "person-nadia-cho", tenant_id: "tenant-migration-demo", roles: ["sponsor"], display_name: "Nadia Cho", email: "nadia.cho@example.com" },
    { id: "person-priya-nair", tenant_id: "tenant-migration-demo", roles: ["applicant"], display_name: "Priya Nair", email: "priya.nair@example.com" },
    { id: "person-hr-recruiter", tenant_id: "tenant-hr-demo", roles: ["recruiter"], display_name: "Jordan Demo", email: "jordan.demo@example.com" },
    { id: "person-oliver-king", tenant_id: "tenant-hr-demo", roles: ["candidate"], display_name: "Oliver King", email: "oliver.king@example.com" },
    { id: "person-sara-lee", tenant_id: "tenant-hr-demo", roles: ["hiring_manager"], display_name: "Sara Lee", email: "sara.lee@example.com" },
    { id: "person-hana-yusuf", tenant_id: "tenant-hr-demo", roles: ["candidate"], display_name: "Hana Yusuf", email: "hana.yusuf@example.com" },
    { id: "person-marcus-reed", tenant_id: "tenant-hr-demo", roles: ["candidate"], display_name: "Marcus Reed", email: "marcus.reed@example.com" },
    { id: "person-kiara-tan", tenant_id: "tenant-hr-demo", roles: ["hiring_manager"], display_name: "Kiara Tan", email: "kiara.tan@example.com" },
  ],
  cases: [
    {
      id: "case-mig-001",
      tenant_id: "tenant-migration-demo",
      vertical: "migration",
      reference: "MIG-DEMO-001",
      title: "Partner visa evidence collection",
      subject_person_id: "person-amina-hart",
      secondary_person_id: "person-rahul-hart",
      owner_person_id: "person-mig-agent",
      pipeline_state: "document_collection",
      priority: "high",
      opened_on: "2026-07-15",
    },
    {
      id: "case-mig-002",
      tenant_id: "tenant-migration-demo",
      vertical: "migration",
      reference: "MIG-DEMO-002",
      title: "Skilled visa compliance check",
      subject_person_id: "person-daniel-cho",
      secondary_person_id: "person-nadia-cho",
      owner_person_id: "person-mig-agent",
      pipeline_state: "compliance_check",
      priority: "medium",
      opened_on: "2026-07-11",
    },
    {
      id: "case-mig-003",
      tenant_id: "tenant-migration-demo",
      vertical: "migration",
      reference: "MIG-DEMO-003",
      title: "Graduate visa lodgement pack",
      subject_person_id: "person-priya-nair",
      owner_person_id: "person-mig-agent",
      pipeline_state: "ready_outcome",
      priority: "low",
      opened_on: "2026-07-09",
    },
    {
      id: "case-hr-001",
      tenant_id: "tenant-hr-demo",
      vertical: "hr",
      reference: "HR-DEMO-001",
      title: "Operations coordinator candidate",
      subject_person_id: "person-oliver-king",
      secondary_person_id: "person-sara-lee",
      owner_person_id: "person-hr-recruiter",
      pipeline_state: "intake",
      priority: "medium",
      opened_on: "2026-07-18",
    },
    {
      id: "case-hr-002",
      tenant_id: "tenant-hr-demo",
      vertical: "hr",
      reference: "HR-DEMO-002",
      title: "Customer success candidate",
      subject_person_id: "person-hana-yusuf",
      secondary_person_id: "person-kiara-tan",
      owner_person_id: "person-hr-recruiter",
      pipeline_state: "document_collection",
      priority: "high",
      opened_on: "2026-07-14",
    },
    {
      id: "case-hr-003",
      tenant_id: "tenant-hr-demo",
      vertical: "hr",
      reference: "HR-DEMO-003",
      title: "Placement pack review",
      subject_person_id: "person-marcus-reed",
      secondary_person_id: "person-kiara-tan",
      owner_person_id: "person-hr-recruiter",
      pipeline_state: "compliance_check",
      priority: "medium",
      opened_on: "2026-07-10",
    },
  ],
  document_requests: [
    { id: "doc-mig-001-passport", tenant_id: "tenant-migration-demo", case_id: "case-mig-001", person_id: "person-amina-hart", checklist_key: "passport_identity", status: "received", due_on: "2026-07-22", last_requested_at: "2026-07-16T01:00:00Z" },
    { id: "doc-mig-001-sponsor", tenant_id: "tenant-migration-demo", case_id: "case-mig-001", person_id: "person-rahul-hart", checklist_key: "sponsor_financials", status: "requested", due_on: "2026-07-25", last_requested_at: "2026-07-21T03:20:00Z" },
    { id: "doc-mig-001-police", tenant_id: "tenant-migration-demo", case_id: "case-mig-001", person_id: "person-amina-hart", checklist_key: "police_check", status: "missing", due_on: "2026-07-29", last_requested_at: "2026-07-21T03:20:00Z" },
    { id: "doc-mig-002-visa", tenant_id: "tenant-migration-demo", case_id: "case-mig-002", person_id: "person-daniel-cho", checklist_key: "visa_history", status: "received", due_on: "2026-07-18", last_requested_at: "2026-07-12T06:15:00Z" },
    { id: "doc-mig-002-medical", tenant_id: "tenant-migration-demo", case_id: "case-mig-002", person_id: "person-daniel-cho", checklist_key: "medical_check", status: "review_required", due_on: "2026-07-24", last_requested_at: "2026-07-17T02:00:00Z" },
    { id: "doc-mig-003-passport", tenant_id: "tenant-migration-demo", case_id: "case-mig-003", person_id: "person-priya-nair", checklist_key: "passport_identity", status: "received", due_on: "2026-07-15", last_requested_at: "2026-07-10T02:10:00Z" },
    { id: "doc-mig-003-police", tenant_id: "tenant-migration-demo", case_id: "case-mig-003", person_id: "person-priya-nair", checklist_key: "police_check", status: "received", due_on: "2026-07-16", last_requested_at: "2026-07-10T02:10:00Z" },
    { id: "doc-hr-001-cv", tenant_id: "tenant-hr-demo", case_id: "case-hr-001", person_id: "person-oliver-king", checklist_key: "cv", status: "received", due_on: "2026-07-20", last_requested_at: "2026-07-18T05:45:00Z" },
    { id: "doc-hr-001-rtw", tenant_id: "tenant-hr-demo", case_id: "case-hr-001", person_id: "person-oliver-king", checklist_key: "right_to_work", status: "missing", due_on: "2026-07-28", last_requested_at: "2026-07-20T05:45:00Z" },
    { id: "doc-hr-002-ref", tenant_id: "tenant-hr-demo", case_id: "case-hr-002", person_id: "person-hana-yusuf", checklist_key: "references", status: "requested", due_on: "2026-07-22", last_requested_at: "2026-07-21T00:30:00Z" },
    { id: "doc-hr-002-contract", tenant_id: "tenant-hr-demo", case_id: "case-hr-002", person_id: "person-hana-yusuf", checklist_key: "contract_pack", status: "expired", due_on: "2026-07-21", last_requested_at: "2026-07-17T04:00:00Z" },
    { id: "doc-hr-003-contract", tenant_id: "tenant-hr-demo", case_id: "case-hr-003", person_id: "person-marcus-reed", checklist_key: "contract_pack", status: "received", due_on: "2026-07-19", last_requested_at: "2026-07-12T01:00:00Z" },
    { id: "doc-hr-003-onboarding", tenant_id: "tenant-hr-demo", case_id: "case-hr-003", person_id: "person-marcus-reed", checklist_key: "onboarding_forms", status: "review_required", due_on: "2026-07-26", last_requested_at: "2026-07-19T01:00:00Z" },
  ],
  deadlines: [
    { id: "deadline-mig-001-evidence", tenant_id: "tenant-migration-demo", case_id: "case-mig-001", kind: "evidence_due", label: "Evidence due", due_on: "2026-07-29", status: "at_risk", severity: "high" },
    { id: "deadline-mig-002-expiry", tenant_id: "tenant-migration-demo", case_id: "case-mig-002", kind: "visa_expiry", label: "Visa expiry", due_on: "2026-08-12", status: "on_track", severity: "medium" },
    { id: "deadline-mig-003-lodge", tenant_id: "tenant-migration-demo", case_id: "case-mig-003", kind: "lodgement_target", label: "Lodgement target", due_on: "2026-08-02", status: "met", severity: "low" },
    { id: "deadline-hr-001-interview", tenant_id: "tenant-hr-demo", case_id: "case-hr-001", kind: "interview", label: "Interview", due_on: "2026-07-28", status: "on_track", severity: "medium" },
    { id: "deadline-hr-002-offer", tenant_id: "tenant-hr-demo", case_id: "case-hr-002", kind: "offer", label: "Offer target", due_on: "2026-07-22", status: "overdue", severity: "high" },
    { id: "deadline-hr-003-placement", tenant_id: "tenant-hr-demo", case_id: "case-hr-003", kind: "placement", label: "Placement target", due_on: "2026-08-05", status: "at_risk", severity: "medium" },
  ],
  follow_up_threads: [
    { id: "thread-mig-001-sponsor", tenant_id: "tenant-migration-demo", case_id: "case-mig-001", channel: "email", participant_person_id: "person-rahul-hart", status: "draft_due", provider: "mock", last_contact_at: "2026-07-21T03:20:00Z", next_action: "Draft evidence reminder for sponsor financials and police check." },
    { id: "thread-mig-002-medical", tenant_id: "tenant-migration-demo", case_id: "case-mig-002", channel: "whatsapp", participant_person_id: "person-daniel-cho", status: "waiting", provider: "mock", last_contact_at: "2026-07-20T06:10:00Z", next_action: "Wait for mock reply before compliance review." },
    { id: "thread-mig-003-ready", tenant_id: "tenant-migration-demo", case_id: "case-mig-003", channel: "email", participant_person_id: "person-priya-nair", status: "closed", provider: "mock", last_contact_at: "2026-07-18T00:20:00Z", next_action: "" },
    { id: "thread-hr-001-rtw", tenant_id: "tenant-hr-demo", case_id: "case-hr-001", channel: "email", participant_person_id: "person-oliver-king", status: "draft_due", provider: "mock", last_contact_at: "2026-07-20T05:45:00Z", next_action: "Draft right-to-work evidence reminder before interview." },
    { id: "thread-hr-002-ref", tenant_id: "tenant-hr-demo", case_id: "case-hr-002", channel: "whatsapp", participant_person_id: "person-hana-yusuf", status: "escalated", provider: "mock", last_contact_at: "2026-07-21T00:30:00Z", next_action: "Escalate overdue references and expired contract pack to recruiter." },
    { id: "thread-hr-003-onboarding", tenant_id: "tenant-hr-demo", case_id: "case-hr-003", channel: "email", participant_person_id: "person-marcus-reed", status: "waiting", provider: "mock", last_contact_at: "2026-07-19T01:00:00Z", next_action: "Wait for onboarding form clarification." },
  ],
  audit_events: [
    { id: "audit-mig-001", tenant_id: "tenant-migration-demo", case_id: "case-mig-001", actor: "agent", action: "draft_follow_up", reason: "Sponsor financial evidence and police check are not received before evidence due date.", created_at: "2026-07-23T00:10:00Z" },
    { id: "audit-mig-002", tenant_id: "tenant-migration-demo", case_id: "case-mig-002", actor: "agent", action: "flag_review", reason: "Medical check is received but needs human compliance review; no migration advice generated.", created_at: "2026-07-23T00:20:00Z" },
    { id: "audit-mig-003", tenant_id: "tenant-migration-demo", case_id: "case-mig-003", actor: "agent", action: "mark_ready", reason: "Required synthetic documents are received and lodgement target is marked met.", created_at: "2026-07-23T00:30:00Z" },
    { id: "audit-hr-001", tenant_id: "tenant-hr-demo", case_id: "case-hr-001", actor: "agent", action: "draft_follow_up", reason: "Right-to-work evidence is missing before the interview date.", created_at: "2026-07-23T00:40:00Z" },
    { id: "audit-hr-002", tenant_id: "tenant-hr-demo", case_id: "case-hr-002", actor: "agent", action: "escalate", reason: "Reference checks are requested and contract pack is expired after the offer target; no hiring decision generated.", created_at: "2026-07-23T00:50:00Z" },
    { id: "audit-hr-003", tenant_id: "tenant-hr-demo", case_id: "case-hr-003", actor: "agent", action: "flag_review", reason: "Onboarding forms require recruiter review before placement target.", created_at: "2026-07-23T01:00:00Z" },
  ],
};

assertBackOfficeData(demoBackOfficeData);
