// Commit generated brief data to the current agent branch, publish it as a PR,
// and merge via GitHub's PR path when branch protection allows it.

import { execFileSync } from "node:child_process";
import { existsSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { BRIEFS_PATH } from "./build-briefs.mjs";

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, "..", "..");
const VALID_TYPES = new Set(["morning", "eod", "weekly", "monthly", "quarterly", "yearly"]);

function output(cmd, args, opts = {}) {
  return execFileSync(cmd, args, {
    cwd: ROOT,
    encoding: "utf8",
    stdio: ["ignore", "pipe", "pipe"],
    env: opts.env || process.env,
  }).trim();
}

function run(cmd, args, opts = {}) {
  execFileSync(cmd, args, {
    cwd: ROOT,
    stdio: "inherit",
    env: opts.env || process.env,
  });
}

function git(...args) {
  return output("git", args);
}

function gh(...args) {
  return output("gh", args);
}

function selectedType() {
  const idx = process.argv.indexOf("--type");
  return (idx >= 0 ? process.argv[idx + 1] : process.env.BRIEF_TYPE || "").toLowerCase();
}

function branchName() {
  const branch = git("branch", "--show-current");
  if (!branch) throw new Error("brief PR publication requires a named Git branch");
  return branch;
}

function todayStamp() {
  return new Date().toISOString().replace(/[-:]/g, "").replace(/\..+$/, "Z").toLowerCase();
}

function ensurePublicationBranch(type) {
  const current = branchName();
  if (!["main", "master"].includes(current)) return current;

  const branch = `agent/briefs/${type}-${todayStamp()}`;
  git("switch", "-c", branch);
  return branch;
}

function latestBrief(type) {
  if (!existsSync(BRIEFS_PATH)) return null;
  const briefs = JSON.parse(readFileSync(BRIEFS_PATH, "utf8"));
  return Array.isArray(briefs)
    ? briefs.filter((brief) => brief.type === type)
      .sort((a, b) => String(b.generated_at || "").localeCompare(String(a.generated_at || "")))[0]
    : null;
}

function briefDate(brief, type) {
  const idDate = /\d{4}-\d{2}-\d{2}/.exec(brief?.id || "");
  return idDate ? idDate[0] : `${type}-${todayStamp()}`;
}

function prBodyFile({ type, branch, commit, brief }) {
  const dir = mkdtempSync(join(tmpdir(), "brief-pr-"));
  const file = join(dir, "body.md");
  const id = brief?.id || `${type} brief`;
  writeFileSync(file, [
    "## Summary",
    "",
    `- Publishes \`${id}\` to Mission Control brief data.`,
    "- Uses a pull request because `main` is protected from direct pushes.",
    "",
    "## Validation",
    "",
    `- \`GIT_COMMIT=1 npm run briefs:build -- --type ${type}\``,
    "",
    "## Generated By",
    "",
    `- Branch: \`${branch}\``,
    `- Commit: \`${commit}\``,
    "",
  ].join("\n"));
  return { dir, file };
}

function viewPr(branch) {
  try {
    return JSON.parse(gh("pr", "view", branch, "--json", "number,url,state,isDraft"));
  } catch {
    return null;
  }
}

function createPr({ type, branch, brief }) {
  const commit = git("rev-parse", "--short", "HEAD");
  const title = `chore(mission-control): publish ${type} brief ${briefDate(brief, type)}`;
  const body = prBodyFile({ type, branch, commit, brief });
  try {
    const url = gh("pr", "create", "--base", "main", "--head", branch, "--title", title, "--body-file", body.file);
    return viewPr(branch) || { url };
  } finally {
    rmSync(body.dir, { recursive: true, force: true });
  }
}

function mergePr(pr) {
  if (process.env.BRIEF_PR_MERGE === "0") {
    console.log(`PR left open by BRIEF_PR_MERGE=0: ${pr.url}`);
    return;
  }

  try {
    run("gh", ["pr", "merge", String(pr.number || pr.url), "--squash"]);
    console.log(`PR merged through GitHub: ${pr.url}`);
  } catch (err) {
    if (process.env.BRIEF_PR_MERGE_REQUIRED === "1") throw err;
    console.warn(`PR left open; merge was not available yet: ${pr.url}`);
  }
}

const type = selectedType();
if (!VALID_TYPES.has(type)) {
  console.error("usage: npm run briefs:publish-pr -- --type <morning|eod|weekly|monthly|quarterly|yearly>");
  process.exit(1);
}

const branch = ensurePublicationBranch(type);
const before = git("rev-parse", "HEAD");
const buildEnv = { ...process.env, GIT_COMMIT: "1" };
delete buildEnv.GIT_PUSH;

run("npm", ["run", "briefs:build", "--", "--type", type], { env: buildEnv });

const after = git("rev-parse", "HEAD");
if (after === before) {
  console.log("brief data unchanged; no PR opened");
  process.exit(0);
}

run("git", ["push", "-u", "origin", `HEAD:${branch}`]);

const brief = latestBrief(type);
const pr = viewPr(branch) || createPr({ type, branch, brief });
console.log(`brief PR ready: ${pr.url}`);
mergePr(pr);
